Updated vcml and integrated arm64_cpu_env into arm64_cpu
aut0/avp64 pull request #7
Opened 2021-10-07 15:37 UTC by nbosb

* Updated vcml submodule to newest version
* integrated `arm64_cpu_env` into `arm64_cpu`
* implemented `disassemble` function

2021-10-07 15:49 UTC, aut0 commented on include/avp64/arm64_cpu.h
> +
Remove white space

2021-10-07 15:51 UTC, aut0 commented on src/arm64_cpu.cpp
> +    memory_protector::memory_protector():
Revert unnecessary change

2021-10-07 15:52 UTC, aut0 commented on src/arm64_cpu.cpp
> +        val = 0x0000000000000000; // init value because vcml doesn't -> necessary, if reg is smaller than 64 bit
Please explain this to me at some point

2021-10-07 15:53 UTC, aut0 commented on src/arm64_cpu.cpp
> +    arm64_cpu::arm64_cpu(const sc_core::sc_module_name &nm, vcml::u64 procid, vcml::u64 coreid):
I like to do : and , at the beginning

2021-10-07 15:54 UTC, aut0 commented on src/system.cpp
> +        vcml::log_info(" ");
Why?

2021-10-07 15:57 UTC, aut0 commented on src/system.cpp
> +        ss.str("");
What does this do?

2021-10-07 15:59 UTC, aut0 commented on .gitignore
> +.vscode
Should be in an extra commit

2021-10-07 16:00 UTC, aut0 commented on include/avp64/aarch64_regs.h
> +        // { , "ESR_EL1", 8, VCML_ACCESS_READ },
Never check in commented out code

2021-10-07 16:00 UTC, aut0 commented on include/avp64/aarch64_regs.h
> +        // { 157, "Z0", 256, VCML_ACCESS_READ_WRITE },
Same

2021-10-07 16:00 UTC, aut0 commented on include/avp64/aarch64_regs.h
> +        // { 391, "FPSID", 4, VCML_ACCESS_READ_WRITE },
same

2021-10-07 16:01 UTC, aut0 commented on src/arm64_cpu.cpp
> +    arm64_cpu_env::arm64_cpu_env():
Unnecessary change

2021-10-07 16:01 UTC, aut0 commented on include/avp64/aarch64_regs.h
> +        { 0,  "X0",  8, VCML_ACCESS_READ_WRITE },
I'd squash the entire commit with the first one.

2021-10-07 16:02 UTC, aut0 commented on include/avp64/arm64_cpu.h
> +    class arm64_cpu :
I prefer to do this in one line as long as it isn't too long. Probably clang-tidy?

2021-10-07 16:05 UTC, nbosb commented on src/arm64_cpu.cpp
> +        val = 0x0000000000000000; // init value because vcml doesn't -> necessary, if reg is smaller than 64 bit
qemu uses memcpy to copy the register value into the 64-bit variable (see [implementation](https://github.com/snps-virtualprototyping/ocx-qemu-arm/blob/6f4191aa999c745f44cde3daea0d0f43ae466dfe/src/armcore.cpp#L519)). Only the number of bytes are updated which are in the register (4 for a 32-bit register). The val variable comes from [target.cpp](https://github.com/janweinstock/vcml/blob/master/src/vcml/debugging/target.cpp#L25) and is not initialized. If the register is 32bit wide, only 32bit of the (uninitialized) 64bit are updated which might lead to false results (and an error because the [max valid value check](https://github.com/janweinstock/vcml/blob/master/src/vcml/debugging/target.cpp#L33) fails)

2021-10-07 16:05 UTC, nbosb commented on src/system.cpp
> +        vcml::log_info(" ");
Otherwise, it results in `error: zero-length gnu_printf format string [-Werror=format-zero-length]`

2021-10-07 16:30 UTC, nbosb commented on src/system.cpp
> +        ss.str("");
It clears the stringstream. Otherwise, the ss of `m_gic.execute` is concatenated to the one from `m_bus.execute`.
However, `m_bus`and `m_gic`do not implement the command "show"

2021-10-08 06:48 UTC, aut0 commented on src/system.cpp
> +        vcml::log_info(" ");
I wonder why the empty print is here in the first place

2021-10-08 12:38 UTC, aut0 commented on src/arm64_cpu.cpp
> +    bool arm64_cpu::disassemble(vcml::u8 *ibuf, vcml::u64 &addr, std::string &code) {
Check if OCX can do this

2021-10-12 11:28 UTC, aut0 requested changes

2021-10-12 11:28 UTC, aut0 commented on src/arm64_cpu.cpp
> +        // u64 disassemble(u64 addr, char* buf, size_t bufsz)
Remove comment

2021-10-12 11:28 UTC, aut0 commented on src/arm64_cpu.cpp
> +        size_t bufsz = 1024;
100 should be enough

2021-10-12 11:31 UTC, merged

2021-10-12 11:32 UTC, aut0 commented
Good work! Thank you for your contribution.